config/routes.rb
Rails.application.routes.draw do
  devise_scope :end_user do
    post 'end_users/guest_sign_in', to: 'public/sessions#guest_sign_in'
  end
  devise_for :end_users, controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
  }
  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
  }

  namespace :admin do
    root to: 'end_users#index'
    resources :end_users, only: %i[show edit update]
    resources :posts, only: %i[index show destroy] do
      resources :post_comments, only: %i[destroy]
    end
  end

  scope module: 'public' do
    root to: 'homes#top'

    resources :end_users, only: %i[show edit update destroy] do
      member do
        get 'confirm', 'follows', 'followers','post_comment'
        patch 'withdraw'
      end
      collection do
        get 'search'
      end
      resource :relationships, only: %i[create destroy]

    end
    resources :notifications, only: %i[index]
    delete :notifications, to: "notifications#destroy_all"

    resources :posts, only: %i[index create show edit update destroy] do
      member do
        delete :delete_image
      end
      collection do
        get 'search'
      end
      get :bookmarks, on: :collection
      resource :likes, only: %i[create destroy]
      resource :bookmarks, only: %i[create destroy]
      resources :post_comments, only: %i[create destroy]
    end
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "EndUser"
  belongs_to :followed, class_name: "EndUser"
  has_one :notification, as: :subject, dependent: :destroy
  validates :follower,    presence: true
  validates :followed,    presence: true
  validates :follower_id, uniqueness: { scope: :followed_id }
  after_create_commit :create_notifications

private

  def create_notifications
    Notification.create(subject: self, end_user: followed, action_type: :follwed_me)
    if followed.email_status == ("0" || "2")
      EndUserMailer.notification_follow_email(followed, follower).deliver_now
    end
  end
  # フォロー元とフォロー先のユーザーが同じであるか確認する
  def cannot_follow_self
    if follower_id == followed_id
      errors.add(:base, "自分自身をフォローすることはできません")
    end
  end
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/views/relationships/_btn.html.erb
<% if current_end_user.following?(end_user) %>
  <%= link_to "フォロー中", end_user_relationships_path(end_user), method: :delete, remote: :true, data: {"turbolinks" => false} , class:"btn btn-outline-danger btn-lg rounded-pill fs-6" %>
<% else %>
  <%= link_to "フォローする", end_user_relationships_path(end_user), method: :post, remote: :true, data: {"turbolinks" => false} , class:"btn btn-outline-primary btn-lg rounded-pill fs-6" %>
<% end %>

app/views/relationships/create.js.erb
$('#follow-<%= @end_user.id %>').html("<%= j(render 'btn', end_user: @end_user) %>");

app/views/relationships/destroy.js.erb
$('#follow-<%= @end_user.id %>').html("<%= j(render 'btn', end_user: @end_user) %>");