config/routes.rb
Rails.application.routes.draw do
  devise_scope :end_user do
    post 'end_users/guest_sign_in', to: 'public/sessions#guest_sign_in'
  end
  devise_for :end_users, controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
  }
  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
  }

  namespace :admin do
    root to: 'end_users#index'
    resources :end_users, only: %i[show edit update]
    resources :posts, only: %i[index show destroy] do
      resources :post_comments, only: %i[destroy]
    end
  end

  scope module: 'public' do
    root to: 'homes#top'

    resources :end_users, only: %i[show edit update destroy] do
      member do
        get 'confirm', 'follows', 'followers','post_comment'
        patch 'withdraw'
      end
      collection do
        get 'search'
      end
      resource :relationships, only: %i[create destroy]

    end
    resources :notifications, only: %i[index]
    delete :notifications, to: "notifications#destroy_all"

    resources :posts, only: %i[index create show edit update destroy] do
      member do
        delete :delete_image
      end
      collection do
        get 'search'
      end
      get :bookmarks, on: :collection
      resource :likes, only: %i[create destroy]
      resource :bookmarks, only: %i[create destroy]
      resources :post_comments, only: %i[create destroy]
    end
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/post.rb
class Post < ApplicationRecord
  has_many_attached :post_images
  belongs_to :end_user
  has_many :likes,         dependent: :destroy
  has_many :bookmarks,     dependent: :destroy
  has_many :post_comments, dependent: :destroy
  # ブックマークした投稿を取得する
  has_many :bookmark_posts,  through: :bookmarks,  source: :post
  has_many :liked_end_users, through: :likes,      source: :end_user
  has_one  :notification,         as: :subject, dependent: :destroy

  validate  :image_type, :image_size, :image_length
  validates :body, presence: true, length: { in: 2..500, message: "2文字以上、500文字以内にする必要があります" }

# 公開状態かつ、退会していないユーザーの投稿だけ取得する
  scope :public_posts, -> { joins(:end_user).where(end_users: { private_status: false, is_deleted: false }) }
  scope :latest,       -> { order(created_at: :desc) }
  scope :like_count,   -> { posts_like_count }
  scope :follows,      -> { posts_current_end_user_follow }

  # likesの中にend_user.idがあるか聞いている
  def liked_by?(end_user)
    likes.exists?(end_user_id: end_user.id)
  end

  def bookmarked_by?(end_user)
    bookmarks.exists?(end_user_id: end_user.id)
  end
  
  def latest_comment
    post_comments.order(created_at: :desc).first
  end

  private

  def image_type
    post_images.each do |image|
      unless image.blob.content_type.in?(%('image/jpeg image/png'))
        image.destroy
        errors.add(:post_images, 'はjpegまたはpng形式でアップロードしてください')
      end
    end
  end

  def image_size
    post_images.each do |image|
      if image.blob.byte_size > 3.megabytes
        image.destroy
        errors.add(:post_images, "は1つのファイル3MB以内にしてください")
      end
    end
  end

  def image_length
    if post_images.length > 4
      post_images.each do |image|
        image.destroy
        errors.add(:post_images, "は1投稿に付き4枚以内にしてください")
      end
    end
  end

  def self.ransackable_attributes(auth_object = nil)
    ["body", "created_at", "likes_count"]
  end
  
  def self.ransackable_associations(auth_object = nil)
    ["end_user"]
  end
  # 一ヶ月以内に作成された投稿を対象にいいねが多い順に並べる
  def self.posts_like_count
    to   = Time.current.at_end_of_day
    from = 1.month.ago.beginning_of_day
    left_outer_joins(:likes).where(likes: { created_at: from..to })
                            .order(likes_count: :desc)
                            .includes(:end_user)
                            .or(left_outer_joins(:likes).where(likes: { id: nil }))
  end

  def self.posts_current_end_user_follow
    self.where(end_user_id: [current_end_user.id, *current_end_user.
               following_end_users_ids]).order(created_at: :desc)

  end

end

app/controllers/admin/posts_controller.rb
class Admin::PostsController < ApplicationController
  before_action :authenticate_admin!
  def index
    if params[:oldest]
      @posts = Post.all.order(created_at: :asc).page(params[:page]).per(10)
    else
      @posts = Post.all.order(created_at: :desc).page(params[:page]).per(10)
    end
  end

  def show
    @post = Post.find(params[:id])
    @post_comments = @post.post_comments.order(created_at: :desc).page(params[:page]).per(10)
  end
  
  def destroy
    @post = Post.find(params[:id])
    if @post.destroy
      redirect_to admin_posts_path
      flash.now[:secondary] = "削除に成功しました"
    else
      @posts = Post.all.order(created_at: :desc).page(params[:page]).per(10)
      render 'show'
      flash.now[:secondary] = "削除は失敗しました"
    end
  end
end

app/helpers/admin/posts_helper.rb
module Admin::PostsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/admin/posts/index.html.erb
<% content_for(:title, "管理用：投稿一覧") %>
<%= render 'layouts/header' %>
<%= render 'layouts/back' %>
<%= render 'layouts/flash' %>

<div class="container-xl mt-5">
  <div class="row">
    <div class="col-1"></div>
    <div class="col-10 ps-0">
      <ul id="tab-menu" class="nav-tabs nav">
        <li id="new-tab" class="nav-item text-center w-50" >
           <%= link_to "新しい順", admin_posts_path, class:"nav-link bg-light fs-6" %>
        </li>
        <li id="follow-tab" class="nav-item text-center w-50">
           <%= link_to "古い順", admin_posts_path(oldest: "true") , class:"nav-link bg-light fs-6" %>
        </li>
      </ul>
      <% @posts.each do |post_list| %>
        <div class="container border p-3 ">
          <div class="row">
            <div class="col-1">
              <%= image_tag post_list.end_user.profile_image, size:'60x60', class:"rounded-circle shadow-sm" %>
            </div>
            <div class="col-8 pl-3">
              <div class="post-user">
                <%= link_to post_list.end_user.name, admin_end_user_path(post_list.end_user_id), class:'link-dark' %>
                <p class="fs-6 text-secondary d-inline">
                  <%= post_list.end_user.unique_id %>
                </p>
              </div>
      
              <div class="post-body">
                <p><%= post_list.body %></p>
                <div class="d-flex flex-wrap">
                  <% if post_list.post_images.attached? %>
                    <% post_list.post_images.each do |image| %>
                      <div class="w-50 mb-1">
                        <%= image_tag image.variant(resize:'320x200>').processed %>
                      </div>
                    <% end %>
                  <% end %>
                </div>
              </div>
            </div>
            <div class="col-3 border-left">
              <%= link_to "投稿を削除する", admin_post_path(post_list), method: :delete, "data-confirm" => "本当に削除しますか？", class:"link-secondary fs-6" %>
              <p><%= link_to "投稿の詳細", admin_post_path(post_list.id), class:"link-secondary" %></p>
              <p class="fs-6">コメント<%= post_list.post_comments.count %></p>
              <p class="fs-6">いいね数<%= post_list.likes.count %></p>
              <p class="fs-6">ブックマーク数<%= post_list.bookmarks.count %></p>
            </div>
          </div>
        </div>
      <% end %>
      <div class="pageantion-on text-center m-3">
        <%= paginate @posts %>
      </div>
    </div>
  </div>
</div>

app/views/admin/posts/show.html.erb
<% content_for(:title, "管理用：投稿詳細") %>
<%= render 'layouts/header' %>
<%= render 'layouts/back' %>
<%= render 'layouts/flash' %>
<div class="container border p-3 ">
  <div class="row">
    <div class="col-1">
      <%= image_tag @post.end_user.profile_image, size:'60x60', class:"rounded-circle shadow-sm" %>
    </div>
    <div class="col-8 pl-3">
      <div class="post-user">
        <%= link_to @post.end_user.name, admin_end_user_path(@post.end_user_id), class:'link-dark' %>
        <p class="fs-6 text-secondary d-inline">
          <%= @post.end_user.unique_id %>
        </p>
      </div>

      <div class="post-body">
        <p><%= @post.body %></p>
        <div class="d-flex flex-wrap">
          <% if @post.post_images.attached? %>
            <% @post.post_images.each do |image| %>
              <!--画像をクリックすると画像のリンクに遷移する-->
              <div class="w-50">
                <%= link_to url_for(image) do %>
                  <%= image_tag image.variant(resize:'320x200>').processed %>
                <% end %>
              </div>
            <% end %>
          <% end %>
        </div>
      </div>
    </div>
    <div class="col-3 border-left">
      <%= link_to "投稿を削除する", admin_post_path(@post), method: :delete, "data-confirm" => "本当に削除しますか？", class:"link-secondary fs-6" %>
      <p><%= link_to "投稿の詳細", admin_post_path(@post.id), class:"link-secondary" %></p>
      <p class="fs-6">コメント<%= @post.post_comments.count %></p>
      <p class="fs-6">いいね数<%= @post.likes.count %></p>
      <p class="fs-6">ブックマーク数<%= @post.bookmarks.count %></p>
    </div>
  </div>
</div>
<% @post_comments.each do |post_comment| %>
<div class="container border p-3 ">
  <div class="row">
    <div class="col-1">
      <%= image_tag post_comment.end_user.profile_image, size:'40x40', class:"rounded-circle shadow-sm" %>
    </div>
    <div class="col-8">
      <div class="post-user">
        <%= link_to post_comment.end_user.name, admin_end_user_path(post_comment.end_user.id), class:'link-dark'  %>
        <p class="fs-6 text-secondary d-inline">
          <%= post_comment.end_user.unique_id %>
        </p>
      </div>
      <div class="post-body">
        <p><%= post_comment.body %></p>
      </div>
    </div>
    <div class="col-3 border-left">
      <%= link_to "コメントを削除する",admin_post_post_comment_path(post_comment.post, post_comment), method: :delete, "data-confirm" => "コメントを削除しますか？", class:"link-secondary fs-6" %>
    </div>
  </div>
</div>
<% end %>