config/routes.rb
Rails.application.routes.draw do
  devise_scope :end_user do
    post 'end_users/guest_sign_in', to: 'public/sessions#guest_sign_in'
  end
  devise_for :end_users, controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
  }
  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
  }

  namespace :admin do
    root to: 'end_users#index'
    resources :end_users, only: %i[show edit update]
    resources :posts, only: %i[index show destroy] do
      resources :post_comments, only: %i[destroy]
    end
  end

  scope module: 'public' do
    root to: 'homes#top'

    resources :end_users, only: %i[show edit update destroy] do
      member do
        get 'confirm', 'follows', 'followers','post_comment'
        patch 'withdraw'
      end
      collection do
        get 'search'
      end
      resource :relationships, only: %i[create destroy]

    end
    resources :notifications, only: %i[index]
    delete :notifications, to: "notifications#destroy_all"

    resources :posts, only: %i[index create show edit update destroy] do
      member do
        delete :delete_image
      end
      collection do
        get 'search'
      end
      get :bookmarks, on: :collection
      resource :likes, only: %i[create destroy]
      resource :bookmarks, only: %i[create destroy]
      resources :post_comments, only: %i[create destroy]
    end
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/end_user.rb
class EndUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  before_create :default_image
  attr_writer   :login

  VALID_PASSWORD_REGEX = /\A(?=.*?[a-z])(?=.*?[\d])[a-z\d]+\z/i.freeze
  validates :password,        presence: true, length: { in: 6..100 },  format: { with: VALID_PASSWORD_REGEX, message: 'は半角英数を両方含む必要があります'}, allow_blank: true
  VALID_EMAIL_REGEX    = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email,          presence: true, length: { minimum: 3 }, uniqueness: true, format: { with: VALID_EMAIL_REGEX }
  VALID_UNIQUE_ID_REGEX = /\A[a-zA-Z0-9_\.]+\z/i
  validates :unique_id,       presence: true, length: { in: 4..20 }, uniqueness:{ case_sensitive: false }, format: { with: VALID_UNIQUE_ID_REGEX, message: 'は英数字、アンダースコア、句読点のみ使用できます'}
  validates :name,            presence: true, length: { in: 2..10 }
  validates :is_deleted,     inclusion: { in: [true, false] }
  validates :private_status, inclusion: { in: [true, false] }
  validate  :validate_unique_id

  has_one_attached :profile_image
  has_many :posts,             dependent: :destroy
  has_many :likes,             dependent: :destroy
  has_many :bookmarks,         dependent: :destroy
  has_many :bookmark_posts,      through: :bookmarks, source: :post # ブックマークした投稿を習得
  has_many :post_comments,     dependent: :destroy
  has_many :notifications
  has_many :followers, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy #フォローした
  has_many :followeds, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy #フォローされた
  has_many :following_end_users, through: :followers, source: :followed #フォロー画面
  has_many :follower_end_users,  through: :followeds, source: :follower #フォロワー画面
  # 公開、非公開に切り替える
  scope :pulished,   -> { where(private_status: true) }
  scope :unpulished, -> { where(private_status: false) }
  enum action_type: { receive_all: 0, comment_receive: 1, follow_receive: 2, receive_block: 3 }

  # emailかuniqur_idどちらか選べるようにしている
  def login
    @login || self.unique_id || self.email
  end

  def self.find_for_database_authentication(warden_conditions)
    conditions = warden_conditions.dup
    if (login = conditions.delete(:login))
      where(conditions.to_h).where(["lower(unique_id) = :value OR lower(email) = :value", { :value => login.downcase }]).first
    elsif conditions.has_key?(:unique_id) || conditions.has_key?(:email)
      where(conditions.to_h).first
    end
  end

  def active_for_authentication?
    super && (is_deleted == false)
  end

  # ユーザが新規登録される際にデフォルト画像を追加する
  def default_image
    if !self.profile_image.attached?
      self.profile_image.attach(io: File.open(Rails.root.join('app/assets/images/no_image.jpg')), filename: 'no_image.jpg', content_type: 'image/jpeg')
    end
  end
  # フォローする
  def follow(end_user_id)
    followers.create(followed_id: end_user_id)
  end
  # フォロー解除
  def unfollow(end_user_id)
    followers.find_by(followed_id: end_user_id).destroy
  end
  # フォローしているか確認
  def following?(end_user)
    following_end_users.include?(end_user)
  end


  def self.guest
    find_or_create_by!(email: 'guest@example.com') do |end_user|
      end_user.unique_id = "guest_id"
      end_user.password = SecureRandom.alphanumeric(20) # 英数字20文字をランダムで形成
      end_user.name = "ゲストさん"
      end_user.introduction = "このアカウントは閲覧用です"
    end
  end

  def self.ransackable_attributes(auth_object = nil)
    ["created_at", "name"]
  end
  
  def self.ransackable_associations(auth_object = nil)
    ["posts"]
  end

private

  # emailかuniqur_idどちらかあるか？
  def validate_unique_id
    if EndUser.where(email: unique_id).exists?
      errors.add(:unique_id, :invalid)
    end
  end

end

app/controllers/admin/end_users_controller.rb
class Admin::EndUsersController < ApplicationController
  before_action :authenticate_admin!
  
  def index
    if params[:oldest]
      @end_users = EndUser.all.order(created_at: :asc).page(params[:page]).per(10)
    else
      @end_users = EndUser.all.order(created_at: :desc).page(params[:page]).per(10)
    end
  end

  def show
    @end_user = EndUser.find(params[:id])
  end

  def edit
    @end_user = EndUser.find(params[:id])
  end

  def update
    @end_user = EndUser.find(params[:id])
    if @end_user.update(end_user_params)
      redirect_to admin_end_user_path(@end_user.id)
      flash.now[:secondary] = '編集を完了しました'
    else
      render :edit
      flash.now[:secondary] = '編集を失敗しました'
    end
  end

private

  def end_user_params
    params.require(:end_user)
    .permit(:name, :unique_id, :email, :date_of_dirth,
            :introduction, :private_status, :is_deleted, :profile_image)
  end

end

app/helpers/admin/end_users_helper.rb
module Admin::EndUsersHelper
end

app/helpers/end_users_helper.rb
module EndUsersHelper
end

app/views/admin/end_users/edit.html.erb
<% content_for(:title, "管理用：#{@end_user.name} さんのプロフィール編集") %>
<%= render 'layouts/header' %>
<%= flash[:notice] %>
<div class="container-xl">
  <div class="row">
    <div style="width: 16%; height: 700px;"></div>
    <div class="col-md-8 col-xl-9 m-3">
      <%= flash[:notice] %>
      <%= render 'layouts/errors', obj: @end_user %>

      <h2 class="text-center">プロフィール編集</h2>
      <%= form_with model: @end_user,  url: admin_end_user_path(@end_user.id) do |f| %>
        <div class="mb-3">
          <%= f.label :表示名, class: 'form-label text-dark' %>
          <%= f.text_field :name, autofocus: true, class: 'form-control', placeholder:"サイトで表示される名前です" %>
        </div>

        <div class="mb-3">
          <%= f.label :ユーザ名, class: 'form-label text-dark' %>
          <%= f.text_field :unique_id, class: 'form-control', placeholder:"英数字、アンダースコア、句読点のみ使用できます" %>
        </div>
        
        <div class="mb-3">
          <%= f.label :プロフィール画像, class: 'form-label text-dark' %>
          <%= f.file_field :profile_image, class: 'form-control', id: "formFile", accept: "image/*" %>
        </div>

        <div class="mb-3">
          <%= f.label :プロフィール文, class: 'form-label text-dark' %>
          <%= f.text_area :introduction, class: 'form-control' %>
        </div>

        <div class="mb-3">
          <%= f.label :メールアドレス, class: 'form-label text-dark' %>
          <%= f.email_field :email, autocomplete: "email", class: 'form-control', placeholder:"name@example.com" %>
        </div>

        <div class="mb-3">
          <%= f.label :生年月日, class: 'form-label text-dark' %>
          <div class="form-date-select">
            <%= f.date_select :date_of_birth, {use_month_numbers: true,start_year: 1930,
                end_year: (Time.now.year - 10), default: Date.new(1999,1,1)}, {class: "form-control d-inline-block", style:"width: 20%;" } %>
          </div>
        </div>
        
        <div class="mb-3">
          <div class="form-check">
            <%= f.radio_button :private_status, 'false', class: 'form-check-input', :type => "checkbox" %>
            <%= f.label :公開, class: 'form-check-label' %>
          </div>
          <div class="form-check">
            <%= f.radio_button :private_status, 'true',class: 'form-check-input' %>
            <%= f.label :非公開, class: 'form-check-label' %>
          </div>
        </div>
        <div class="mb-3">
           <div class="form-check">
            <%= f.radio_button :is_deleted, 'false', class: 'form-check-input', :type => "checkbox" %>
            <%= f.label :有効, class: 'form-check-label' %>
          </div>
          <div class="form-check">
            <%= f.radio_button :is_deleted, 'true',class: 'form-check-input' %>
            <%= f.label :退会, class: 'form-check-label' %>
          </div>
        </div>
        
        <div class="actions mx-auto w-50 mt-5 mb-5" style="height: 65px;">
          <%= f.submit "編集を保存する", class: 'btn btn-primary btn-lg w-100 h-100 fs-5 fw-bold' %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/end_users/index.html.erb
<% content_for(:title, "管理用：会員一覧") %>
<%= render 'layouts/header' %>
<%= render 'layouts/back' %>
<%= render 'layouts/flash' %>

<div class="container-xl mt-5">
  <div class="row">
    <div class="col-1"></div>
    <div class="col-10 ps-0">
      <ul id="tab-menu" class="nav-tabs nav">
        <li id="new-tab" class="nav-item text-center w-50" >
           <%= link_to "新しい順", admin_root_path, class:"nav-link bg-light fs-6" %>
        </li>
        <li id="follow-tab" class="nav-item text-center w-50">
           <%= link_to "古い順", admin_root_path(oldest: "true") , class:"nav-link bg-light fs-6" %>
        </li>
      </ul>
      <% @end_users.each do |end_user| %>
        <div class="container border p-3 ">
          <div class="row">
            <div class="col-1">
              <%= link_to admin_end_user_path(end_user) do %>
                <%= image_tag end_user.profile_image, size:'50x50', class:"rounded-circle shadow-sm" %>
              <% end %>
            </div>
            <div class="col-7">
              <div class="post-user">
                <%= link_to end_user.name, admin_end_user_path(end_user), class:'link-primary' %>
                <p class="fs-6 text-secondary d-inline">
                  <%= end_user.unique_id %>
                </p>
              </div>
    
              <div class="user-body">
                <p><%= end_user.introduction.truncate(50) %></p>
              </div>
            </div>
            <div class="col-4">
              <div class="">
                <p class="d-inline-block text-secondary">フォロー <%= end_user.following_end_users.count %></p>
                <p class="d-inline-block text-secondary">フォロワー <%= end_user.follower_end_users.count %></p>
              </div>
              <div class="">
                <p class="d-inline-block text-secondary">投稿した数 <%= end_user.posts.count %></p>
                <p class="d-inline-block text-secondary">コメントした数 <%= end_user.post_comments.count %></p>
              </div>
            </div>
          </div>
        </div>
        <% end %>
        <div class="pageantion-on text-center m-3">
          <%= paginate @end_users %>
        </div>
    </div>
  </div>
</div>

app/views/admin/end_users/show.html.erb
<% content_for(:title, "管理用：#{@end_user.name} さんのプロフィール") %>
<%= render 'layouts/header' %>
<%= render 'layouts/flash' %>
<div class="container-fuild m-3 mb-0">
  <div class="row">
    <div class="text-center">
      <%= link_to image_tag(@end_user.profile_image, size:'200x200'), url_for(@end_user.profile_image), class:"rounded-circle shadow-sm" %>
    </div>
    <div class="col-2"></div>
    <div class="col-8">
  
      <div class="mx-auto">
        <div class="mb-3">
          <%= link_to "プロフィール編集", edit_admin_end_user_path(@end_user.id), class:"btn btn-primary btn-lg rounded-pill fs-6" %>
        </div>
        <table class="table table-striped">
            <tr>
              <th>ID</th>
              <td><%= @end_user.id %></td>
            </tr>
            <tr>
              <th>表示名</th>
              <td><%= @end_user.name %></td>
            </tr>
            <tr>
              <th>ユーザー名</th>
              <td><%= @end_user.unique_id %></td>
            </tr>
            <tr>
              <th>メールアドレス</th>
              <td><%= @end_user.email %></td>
            </tr>
            <tr>
              <th>生年月日</th>
              <td><%= @end_user.date_of_birth %></td>
            </tr>
            <tr>
              <th>プロフィール文</th>
              <td><%= @end_user.introduction %></td>
            </tr>
            <tr>
              <th>公開状態</th>
              <% if @end_user.private_status == false %>
                <td>公開</td>
              <% else %>
                <td>非公開</td>
              <% end %>
            </tr>
            <tr>
              <th>退会状況</th>
              <% if @end_user.is_deleted == false %>
                <td>有効</td>
              <% else %>
                <td>退会</td>
              <% end %>
            </tr>
            <tr>
              <th>登録日時</th>
              <td><%= @end_user.created_at.to_s(:datetime_jp) %></td>
            </tr>
            <tr>
              <th>更新日時</th>
              <td><%= @end_user.updated_at.to_s(:datetime_jp)  %></td>
            </tr>
        </table>
      </div>
    </div>
  </div>
</div>