config/routes.rb
Rails.application.routes.draw do
  devise_scope :end_user do
    post 'end_users/guest_sign_in', to: 'public/sessions#guest_sign_in'
  end
  devise_for :end_users, controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
  }
  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
  }

  namespace :admin do
    root to: 'end_users#index'
    resources :end_users, only: %i[show edit update]
    resources :posts, only: %i[index show destroy] do
      resources :post_comments, only: %i[destroy]
    end
  end

  scope module: 'public' do
    root to: 'homes#top'

    resources :end_users, only: %i[show edit update destroy] do
      member do
        get 'confirm', 'follows', 'followers','post_comment'
        patch 'withdraw'
      end
      collection do
        get 'search'
      end
      resource :relationships, only: %i[create destroy]

    end
    resources :notifications, only: %i[index]
    delete :notifications, to: "notifications#destroy_all"

    resources :posts, only: %i[index create show edit update destroy] do
      member do
        delete :delete_image
      end
      collection do
        get 'search'
      end
      get :bookmarks, on: :collection
      resource :likes, only: %i[create destroy]
      resource :bookmarks, only: %i[create destroy]
      resources :post_comments, only: %i[create destroy]
    end
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/_back.html.erb
<span id="back" class="back-btn">
  <a href="#" class="text-primary">
    <i class="bi bi-arrow-up-square-fill fs-2"></i>
  </a>
</span>

app/views/layouts/_errors.html.erb
<% if obj.errors.any? %>
  <div class="alert alert-secondary" role="alert">
    <button type="button" class="close" data-dismiss="alert">  &times;</button>
    <ul>
      <% obj.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_flash.html.erb
<% flash.each do |key, value| %>
    <p class="alert alert-secondary">
      <%= value %><button type="button" class="close" data-dismiss="alert">  &times;</button>
    </p>
<% end %>

app/views/layouts/_footer.html.erb
<div class="container-fuild border-top mt-5">
  <div class="row">
    <div class="text-center mt-3">
      <div class="text-secondary">
        <h4>CodeConnect</h4>
        <p>© 2023-2023 CodeConnect</p>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_form_errors.html.erb
<% if obj.errors.include?(attribute) %>
  <% if obj.errors.any? %>
    <div class="alert alert-secondary pb-0 mb-0">
      <button type="button" class="close" data-dismiss="alert">  &times;</button>
      <ul>
        <% obj.errors.full_messages_for(attribute).each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
<% end %>

app/views/layouts/_header.html.erb
<% if admin_signed_in? %>
  <% if request.fullpath.include? "/admin" %>
    <header class="bg-dark border-bottom">
      <nav class="navbar navbar-expand-lg">
        <div class="container-fluid">
          <%= link_to root_path do %>
            <%= image_tag 'CodeConnect.jpg',size:"100%x100%" %>
          <% end %>
          <div class="w-100 text-center">
            <%= link_to "ユーザー一覧", admin_root_path ,class: 'btn btn-primary fs-6' %>
            <%= link_to "投稿一覧", admin_posts_path ,class: 'btn btn-primary mx-5 fs-6' %>
            <%= link_to "ログアウト", destroy_admin_session_path, method: :delete, class: 'btn btn-primary fs-6' %>
          </div>
        </div>
      </nav>
    </header>
  <% end %>
<% elsif end_user_signed_in? %>
  <header class="container-fuild">
    <div class="row">
      <div class="col-12">
        <nav class="navbar navbar-dark bg-dark" style="height: 90px;">
          <div class="container-fluid">
            <div class="mx-auto d-inline-block">
              <div class="d-inline-block">
                <%= search_form_for @q_posts, url: search_posts_path, class:"d-flex" do |f| %>
                  <%= f.search_field :body_cont, class:"form-control mx-auto", placeholder:"投稿検索…", required:"required" %>
                  <%= f.button :type => "submit", class:"btn btn-primary btn-sm ml-3", style:"width: 20%;"  do %>
                    <i class="bi bi-search fs-6 text-light"></i>
                  <% end %>
                <% end %>
              </div>
              <div class="d-inline-block ml-5">
                <%= search_form_for @q_end_users, url: search_end_users_path, class:"d-flex" do |f| %>
                  <%= f.search_field :name_cont, class:"form-control mx-auto", placeholder:"ユーザー検索…", required:"required" %>
                  <%= f.button :type => "submit", class:"btn btn-primary btn-sm ml-3", style:"width: 20%;"  do %>
                    <i class="bi bi-search fs-6 text-light"></i>
                  <% end %>
                <% end %>
              </div>
            </div>
            <%= link_to posts_path do %>
              <%= image_tag 'CodeConnect.jpg',size:"100%x100%" %>
            <% end %>
          </div>
        </nav>
      </div>
    </div>
  </header>
<% end %>

app/views/layouts/_navgation.html.erb
<!-- 新規投稿用モーダル -->
<% if current_end_user.email == 'guest@example.com' %>
  <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">新規で投稿する</h5>
          <button type="button" class="btn-close" data-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
          <p>
            ゲストは新規投稿することはできません。<br>
            投稿を希望する場合は<%= link_to "新規登録",destroy_end_user_session_path, method: :delete, class:"link-primary" %>をお願いします。
          </p>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">閉じる</button>
        </div>
      </div>
    </div>
  </div>
<% else %>
  <div class="modal fade" id="staticBackdrop" data-backdrop="static" data-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="staticBackdropLabel">新規で投稿する</h5>
          <button type="button" class="btn-close" data-dismiss="modal" aria-label="Close"></button>
        </div>
        <%= form_with model: @post, url: posts_path do |f| %>
        <div class="modal-body">
          <h6>本文</h6>
          <%= f.text_area :body, class:"form-control border", style:"height: 400px;" %>
          <h6>画像(１つの投稿に付き4個まで)</h6>
          <%= f.file_field :post_images, accept: "image/*", multiple: true, class:"form-control-sm border"%>
          <div id="new-image"><!-- アップロードした画像があれば表示する--></div>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary fs-6" data-dismiss="modal">閉じる</button>
          <%= f.submit '投稿する', class:"btn btn-primary fs-6" %>
        </div>
        <% end %>
      </div>
    </div>
  </div>
<% end %>

    <div class="d-flex flex-column flex-shrink-0 p-3 text-bg-dark fixed-top" style="width: 16%; height: 700px;">
      <%= link_to end_user_path(current_end_user.id), class:'d-flex align-items-center mb-3 mb-md-0 me-md-auto text-white text-decoration-none' do %>
        <!--画像を加工し、加工済みのデータが有る場合はそのデータを表示する-->
        <%= image_tag current_end_user.profile_image.variant(resize:'60x60!>').processed, class:"rounded-circle align-top mb-auto" %>
        <p class="fs-6 text-secondary mb-0 ml-2">
          <span class="text-light"><%= current_end_user.name %></span>
          <%= current_end_user.unique_id %>
        </p>
      <% end %>
      </a>
      <hr>
      <ul class="nav flex-column mb-auto mt-2">
        <li class="nav-item mt-3">
          <%= link_to posts_path,  class:'nav-link text-light mb-3 pe-1 ps-2', style:'font-size: 15px;', style:'font-size: 15px;' do %>
            <i class="bi bi-house fs-4"></i> ホーム
          <% end %>
        </li>
        <li class="nav-item">
          <%= link_to notifications_path, class:'nav-link text-light mb-3 pe-1 ps-2', style:'font-size: 15px;', style:'font-size: 15px;'  do %>
            <% if current_end_user.notifications.where(checked: false).exists? %>
              <i class="bi bi-bell-fill fs-4"></i>
              <%= current_end_user.notifications.where(checked: false).count %> 通知
            <% else %>
              <i class="bi bi-bell-slash fs-4"></i> 通知
            <% end %>
          <% end %>
          </li>
        <li class="nav-item">
          <%= link_to end_user_path(current_end_user.id),  class:'nav-link text-light mb-3 pe-1 ps-1', style:'font-size: 15px;' do %>
            <i class="bi bi-person fs-3"></i> プロフィール
          <% end %>
        </li>
        <li class="nav-item">
          <%= link_to bookmarks_posts_path , class:'nav-link text-light mb-3 pe-1 ps-2', style:'font-size: 15px;' do %>
            <i class="bi bi-bookmarks fs-4"></i> ブックマーク
          <% end %>
        </li>
        <li class="nav-item">
          <%= button_to destroy_end_user_session_path, method: :delete,  class:'nav-link text-light mb-3 pe-1 ps-2', style:'font-size: 15px;' do %>
            <i class="bi bi-box-arrow-right fs-4"></i> ログアウト
          <% end %>
        </li>
      </ul>
      <hr>
      <div class="dropdown">
        <% if current_end_user.email == 'guest@example.com' %>
          <button type="button" class="btn btn-primary btn-lg fs-6 w-100" data-toggle="modal" data-target="#exampleModal">
            新規投稿
          </button>
        <% else %>
          <button type="button" class="btn btn-primary btn-lg fs-6 w-100" data-toggle="modal" data-target="#staticBackdrop">
            新規投稿
          </button>
        <% end %>
      </div>
    </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= favicon_link_tag asset_path('favicon.ico') %>
    <title><%= content_for?(:title) ? yield(:title) : "でふぉると" %> CodeConnect</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://cdn.jsdelivr.net/npm/bootswatch@5.3.0/dist/sandstone/bootstrap.min.css" rel="stylesheet">

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.0/font/bootstrap-icons.css">

  </head>

  <body>
    <%= yield %>
  </body>
</html>